### PR TITLE
8281969: Bad result for the snippet @link tag if substring/regex consists of whitespace

### PR DESCRIPTION
**Pull request by pavelrappo**
This PR fixes how links inside a snippet treat whitespace.

During the development of the "Snippets" feature, the concern was about presentation of links that contain leading or trailing whitespace. For that reason, any such whitespace was trimmed. I think it's now reasonable to simplify code and say that any such presentation concerns should be solved with presentation tools, such as CSS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8281969](https://bugs.openjdk.org/browse/JDK-8281969): Bad result for the snippet @link tag if substring/regex consists of whitespace

### Reviewers
 * [Jonathan Gibbons](https://openjdk.org/census#jjg) (@jonathan-gibbons - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19 pull/142/head:pull/142` \
`$ git checkout pull/142`

Update a local copy of the PR: \
`$ git checkout pull/142` \
`$ git pull https://git.openjdk.org/jdk19 pull/142/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 142`

View PR using the GUI difftool: \
`$ git pr show -t 142`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19/pull/142.diff">https://git.openjdk.org/jdk19/pull/142.diff</a>

</details>

### CODE REVIEW

**Comment by jonathan-gibbons** [comment]
While maybe not as bad as "garbage in: garbage out", the test case being fixed does have an aspect of "stupid in: stupid out". 

I'm torn between wanting consistency between the different forms of `link` (doc comment tags and snippet markup tags) and consistency between the examples given in the bug report for highlight and link markup tags.

On the other hand, if people want to do something stupid, like link a whitespace character, well, maybe we should let them, even though I think it's a dreadful idea to do so.   Although I must admit, if I'd been the one fixing this, I would have detected and rejected this case, given a warning, and ignored the tag.

**Comment by pavelrappo** [comment]
> I'm torn between wanting consistency between the different forms of `link` (doc comment tags and snippet markup tags) and consistency between the examples given in the bug report for highlight and link markup tags.

One thing to consider is that the snippet's markup `@link` tag is somewhat more powerful than the Standard doclet's `{@link}` tag. The former can be applied to regions that span multiple lines. In that case, we need to decide whether it's going to be a single link or multiple links, one per line.

The simpler, the better.

**Comment by jonathan-gibbons** [comment]
> any such presentation concerns should be solved with presentation tools, such as CSS.

I don't see anything in CSS that would allow the link to not include leading and trailing whitespace.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration

**Review by jonathan-gibbons — APPROVED** [review]

**Pull request closed without merging**
