### PR TITLE
8288112: C2: Error: ShouldNotReachHere() in Type::typerr()

### PR DESCRIPTION
**Pull request by jatin-bhateja**
[JDK-8284960](https://bugs.openjdk.org/browse/JDK-8284960) added new vector IR nodes and target specific backend support for  ReverseByte vector operations.  
For each scalar operation, auto-vectorizer analysis stage checks for existence of vector IR opcode and target specific backend implementation.  While processing scalar IR nodes corresponding to Java SE APIs [Short/Character/Integer/Long].reverseBytes SLP analysis checks passes since relevant support already existed. This bug fix patch handles missing scalar reversebyte opcode checks in SLP backed to enable creation of corresponding vector IR nodes.

A new JBS issue [JDK-8290034](https://bugs.openjdk.org/browse/JDK-8290034) is created to add the missing auto-vectorization support for bit reverse operation targeting JDK mainline.

Kindly review and share your feedback.

Best Regards,
Jatin

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288112](https://bugs.openjdk.org/browse/JDK-8288112): C2: Error: ShouldNotReachHere() in Type::typerr()

### Reviewers
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19 pull/128/head:pull/128` \
`$ git checkout pull/128`

Update a local copy of the PR: \
`$ git checkout pull/128` \
`$ git pull https://git.openjdk.org/jdk19 pull/128/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 128`

View PR using the GUI difftool: \
`$ git pr show -t 128`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19/pull/128.diff">https://git.openjdk.org/jdk19/pull/128.diff</a>

</details>

### CODE REVIEW

**Review by dean-long — COMMENTED** [review]
Looks good to me, but I still have a problem with the error message.  It seems like we could give a better error message if we detected the missing vectorization support earlier.  What do you think?

**Review by vnkozlov — COMMENTED** [review]
Looks good to me. Thank you for fixing it. I will run testing.

**Comment by vnkozlov** [comment]
Failed:
```
test\micro\org\openjdk\bench\java\lang\Longs.java:148: error: incompatible types: possible lossy conversion from long to int
[2022-07-10T21:01:01,470Z]             int r = Long.reverseBytes(longArraySmall[i]);
```

**Comment by jatin-bhateja** [comment]
> test\micro\org\openjdk\bench\java\lang\Longs.java:148: error: incompatible types: possible lossy conversion from long to in

> Looks good to me, but I still have a problem with the error message. It seems like we could give a better error message if we detected the missing vectorization support earlier. What do you think?

Hi @dean-long ,  Thanks for your comments, error occurs because SLP analysis passes all the checks to enable creation vector ReverseByte IR, but SLP backend had this case missing due to which some of the IR nodes were vectorized and were feeding into a scalar ReverseByte node, thus while doing a value computation compiler encounters a meet operation b/w vector and scalar lattice. Since its an error related to internals of JIT compiler it will not be of any use to user and just represent incorrect control path selected by compiler.  With this patch we do not hit the trap any more.

**Comment by jatin-bhateja** [comment]
> @jatin-bhateja Right, a better error message wouldn't be a value-add to users, but if we could detect it sooner, like in SuperWord::output(), that might be useful to compiler engineers debugging issues.

Hi @dean-long , Agree, I have changed the error message generated with -XX:+TraceLoopOpts to be more explicit like.
**SWPointer::output: Unhandled scalar opcode (ReverseBytesI), ShouldNotReachHere, exiting SuperWord**

Since patch already handles the missing scalar case, hence this message will not be generated.

**Review by vnkozlov — COMMENTED** [review]
Looks good. I submitted testing.

**Comment by vnkozlov** [comment]
Tests copyright header validation failed because you forgot `,` after `2022` year in TestLongVect.java and TestShortVect.java.
Otherwise testing results are good.

**Comment by jatin-bhateja** [comment]
> 

Thanks, fixed now

**Review by vnkozlov — APPROVED** [review]
Good.

**Comment by jatin-bhateja** [comment]
Hi @dean-long , kindly approve is the patch version looks ok to you.

**Review by dean-long — APPROVED** [review]

**Comment by jatin-bhateja** [comment]
Thanks @vnkozlov @dean-long.

**Pull request closed without merging**
