### PR TITLE
8288528: broken links in java.desktop

### PR DESCRIPTION
**Pull request by kumarabhi006**
doccheck reports some broken links which are rectified. copyright year updated for files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288528](https://bugs.openjdk.org/browse/JDK-8288528): broken links in java.desktop

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to [286be6eb](https://git.openjdk.org/jdk19/pull/44/files/286be6eb7f83d323b53e9e5184c0c5ecd543044e)
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19 pull/44/head:pull/44` \
`$ git checkout pull/44`

Update a local copy of the PR: \
`$ git checkout pull/44` \
`$ git pull https://git.openjdk.org/jdk19 pull/44/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 44`

View PR using the GUI difftool: \
`$ git pr show -t 44`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19/pull/44.diff">https://git.openjdk.org/jdk19/pull/44.diff</a>

</details>

### CODE REVIEW

**Review by prrace — APPROVED** [review]
Please ensure that "make docs" is happy and looks good.

**Review by aivanov-jdk — COMMENTED** [review]
Should the copyright year be updated?

**Review by aivanov-jdk — APPROVED** [review]

**Pull request closed without merging**
