### PR TITLE
8278469: Test java/nio/channels/FileChannel/LargeGatheringWrite.java times out

### PR DESCRIPTION
**Pull request by bplb**
Modify test directives so that `LargeGatheringWrite` and `MapTest` in `java/nio/channels/FileChannel` are not run concurrently with other tests.

Redirected from https://github.com/openjdk/jdk/pull/9416.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8278469](https://bugs.openjdk.org/browse/JDK-8278469): Test java/nio/channels/FileChannel/LargeGatheringWrite.java times out
 * [JDK-8289526](https://bugs.openjdk.org/browse/JDK-8289526): java/nio/channels/FileChannel/MapTest.java times out

### Reviewers
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19 pull/122/head:pull/122` \
`$ git checkout pull/122`

Update a local copy of the PR: \
`$ git checkout pull/122` \
`$ git pull https://git.openjdk.org/jdk19 pull/122/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 122`

View PR using the GUI difftool: \
`$ git pr show -t 122`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19/pull/122.diff">https://git.openjdk.org/jdk19/pull/122.diff</a>

</details>

### CODE REVIEW

**Comment by bplb** [comment]
It is conjectured that several tests with large memory demands such as these could be failing due to insufficient memory per core on the test node when the tests are run simultaneously.

**Comment by jaikiran** [comment]
Hello Brian, should `java/nio/channels/Channels/ReadXBytes.java` be treated similarly to prevent https://bugs.openjdk.org/browse/JDK-8289470? That test uses `-Xmx12G`, so probably would need to be running exclusively?

**Comment by bplb** [comment]
> Hello Brian, should `java/nio/channels/Channels/ReadXBytes.java` be treated similarly to prevent https://bugs.openjdk.org/browse/JDK-8289470? That test uses `-Xmx12G`, so probably would need to be running exclusively?

Probably. I had been considering because of this [prior comment](https://github.com/openjdk/jdk19/pull/122#issuecomment-1178864972).

**Pull request closed without merging**
